### ISSUE TITLE
Rain trail generation method（雨迹生成方法）

### ISSUE THREAD

**Issue by 18735549442** [cschenxiang/UDR-Mixer#2]
作者大大能分享一下在普通图像上进行雨迹生成的方法吗？感谢！在你们之前的雨天数据集的工作都是通过photoshop进行雨迹生成的吗？

**Comment by cschenxiang** [comment]
> 作者大大能分享一下在普通图像上进行雨迹生成的方法吗？感谢！在你们之前的雨天数据集的工作都是通过photoshop进行雨迹生成的吗？

不好意思，因工作太忙，回复您太晚了。可以参考代码地址如下：
https://github.com/cschenxiang/HQ-RAIN/blob/main/addrain.py

**Comment by 18735549442** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已收到您的邮件。我将尽快给您回复。
